name: "Setup and install"
description: "Node setup and npm install for actions"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: "Setup node"
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - shell: bash
      run: cd client
      run: npm install